@Library('GenericSharedLibPython') _

pipeline {
    agent { label 'slave-node' }

    environment {
        APP_TYPE = "python"
        IMAGE = "flask-app"
        CONTAINER = "flask-container"
    }

    stages {

        stage('Build') {
            steps {
                dir('task-3'){
                    echo "Branch: ${env.BRANCH_NAME}"
                    build(appType: APP_TYPE)
                }
            }
        }

        stage('Test') {
            steps {
                dir('task-3'){
                    test(appType: APP_TYPE)
                }
            }
        }

        stage('Deploy (main only)') {
            when {
                branch 'main'
            }
            steps {
                dir('task-3'){
                    deploy(
                        imageName: IMAGE,
                        containerName: CONTAINER
                    )
               }
            }
        }
    }
}
