pipeline {
    agent { label 'slave-node' }

    environment {
        ENVIRONMENT = 'unknown'
    }

    stages {

        stage('Set Environment') {
            steps {
                script {
                    if (env.BRANCH_NAME.startsWith("dev")) {
                        ENVIRONMENT = "dev"
                    } else if (env.BRANCH_NAME.startsWith("test")) {
                        ENVIRONMENT = "test"
                    } else if (env.BRANCH_NAME.startsWith("prod")) {
                        ENVIRONMENT = "prod"
                    } else {
                        ENVIRONMENT = "unknown"
                    }
                }

                echo "Selected environment = ${ENVIRONMENT}"
            }
        }


        stage('Build') {
            steps {
                echo "===== BUILD STAGE ====="
                echo "Selected Environment: ${ENVIRONMENT}"
                sh 'echo Building the application........'
            }
        }

        stage('Test') {
            steps {
                echo "===== TEST STAGE ====="
                echo "Selected Environment: ${ENVIRONMENT}"
                sh 'echo Running tests.......'
            }
        }

        stage('Deploy') {
            steps {
                echo "===== DEPLOY STAGE ====="
                echo "Deploying to environment: ${ENVIRONMENT}"
                sh """
                    echo Deploying to ${ENVIRONMENT}.......
                """
            }
        }
    }

    post {
        always {
            echo "Pipeline completed for environment: ${ENVIRONMENT}"
        }
    }
}
